### ISSUE TITLE
Default host to localhost instead of empty string?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch-support-diagnostics#100]
User in the field would like to see that we default the host parameter to localhost instead of an empty string for ease of use.
   
```
 -h, --host
       Required field.  Hostname, IP Address, or localhost.  HTTP access must be
       enabled.
       Default: <empty string>
```

**Comment by nemonster** [comment]
Not sure about this one. It's a required field since in 2.x you have to set the network. host explicitly anyway.  If you default it to localhost then if local access isn't enabled it fails.  I'm inclined to leave this one as is.  I'll allow it's a little easier, but you've gotta kinda lazy to not type that in.

**Comment by jpcarey** [comment]
Most elastic tools / libraries default to localhost if no value is provided. Also, 2.2 allowed for binding to [multiple address](https://github.com/elastic/elasticsearch/pull/13954) (ex. `[ "_local_", "_eth0_"]`).

**Comment by nemonster** [comment]
In this case, yes Elasticsearch does default to localhost.  But you can't really use it that way for a production node since at that stage the only way you can connect to it is from that same host.  So it has some utility for a one node cluster that isn't really being used but that's it.  Requiring the user to at least specify a host name is a sanity check of sorts, in the same vein as requiring network.host.  You can even use localhost if you like. You just have to prove to the utility that you kind of know what you are doing.
