### ISSUE TITLE
Add command-line check of JVM flags (e.g. zero based address)

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch-support-diagnostics#123]
see https://www.elastic.co/blog/a-heap-of-trouble

**Comment by nemonster** [comment]
@jasontedor  I have a few questions on how to incorporate this?

From the blog it appears that the easiest way to check this is via the start up messages.  Which should be present in the log.  So if you get a log with a recent start it should be there already and I'd be done.

The issue would be for node instances that have been running for some time.  When that's the case you'd expect the log that would have contained the message to have already rolled over.  And quite possibly aged off.  So the logs wouldn't show you anything unless you had the older logs that contained the startup output.  That's not impossible since you know how long the JVM has been running.  But it does require that they're still in the log directory and we can identify and acquire the log that was there at startup. So not impossible but a probably bit more involved code-wise and no guarantee of success.

It seems as though the only other way of checking via that command line output mechanism would be to start/stop another Java process with the same max heap size as used for the ES instance and trap the output.  Similar to what I do with the system commands in the diagnostic.  I do wonder if there are ramifications when you have a larger heap and you're starting another process with the same -Xmx setting? We generally tell people that running the diagnostic won't have any adverse impact on the running node.  Does that still hold true if you run this kind of check? And would setting -Xms to a low value or just not setting it at all and taking the default of 2MB(?) minimize the risk? 

So there were a couple of other possible avenues I also wanted to explore:

- Is there some way via code to determine whether there's a non-zero base? Since it appears that this is largely implemented under the covers?  Do any lower level operations such as with the bitwise operators produce some identifiable output that can be examined?  I know there's a performance difference but not sure how you'd use that in a health check scenario.
- Or might it be preferable to create some kind of standalone utility for finding the heap size that assures a zero base?  Something similar to the on demand check above.  Where you have a program that starts/stops a Java process with gradually increasing heap sizes until you hit the magic number?  That *is* a little bit more in the prevention mode than diagnostic but it might be easier to implement.

**Comment by jasontedor** [comment]
> It seems as though the only other way of checking via that command line output mechanism would be to start/stop another Java process with the same max heap size as used for the ES instance and trap the output.

That's exactly what I would do. Rather than trying to figure out from the logs whether or not a node was started with a zero-base, instead just take the heap size that was used to start the node (for example, from `jps` output) and then just run:

`$ java -Xms1m -Xmx<max-heap-size> -XX:+UnlockDiagnosticVMOptions -XX:+PrintCompressedOopsMode -version`

and then just dump the contents of that output to the diagnostic.

> And would setting -Xms to a low value or just not setting it at all and taking the default of 2MB(?) minimize the risk?

Note how I force above the minimum heap setting so that the minimal memory will actually be requested from the OS. This should be safe most of the time (it will ultimately depend on the VM commit settings on the node.

> Is there some way via code to determine whether there's a non-zero base?

I don't think it will be anything simple and reliable across OS.

> Or might it be preferable to create some kind of standalone utility for finding the heap size that assures a zero base?

I think the above Java command is the safest option, and what you really want to know is binary whether or not the node was started with zero-based oops.
