### ISSUE TITLE
Calculate count a different way

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch-support-diagnostics#138]
I've seen a diagnostic that had for both `/_cat/count` and `count.json`:

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Trying to query 1020 shards, which is over the limit of 1000. This limit exists because querying many shards at the same time can make the job of the coordinating node very CPU and/or memory intensive. It is usually a better idea to have a smaller number of larger shards. Update [action.search.shard_count.limit] to a greater value if you really want to query that many shards at the same time."
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "Trying to query 1020 shards, which is over the limit of 1000. This limit exists because querying many shards at the same time can make the job of the coordinating node very CPU and/or memory intensive. It is usually a better idea to have a smaller number of larger shards. Update [action.search.shard_count.limit] to a greater value if you really want to query that many shards at the same time."
  },
  "status" : 400
}
```

It'd be great if there were a different way the tool gathered this so that it could be retrieved.

**Comment by nemonster** [comment]
I don't have the full diagnostic run, but I'm curious about a few things.  

* What ES version was the diagnostic run against?
* Whether  the /_stats call that produces indices_stats.json ran successfully?  If it did then the document count ought to be in the _all node. Although if there's indexing going on between that and the _count calls they may not line up exactly.
* Did any of the other REST calls fail?  Other than things where it would be expected like the Shield and Watcher related calls if those weren't installed?

The _cat/count and _count are just shortcuts to get the live document count for the cluster, AFAIK. Checking the action in the source shows that it just makes another internal call to get that. And it's that internal call that's generating the error.  News to me that it fails if you have more than 1000 shards, but that's not documented anywhere. Which does make some sense because it's not the actual REST command that fails. It has no way of knowing that it's asking for too much until it get the message.

So I'm not sure how to proceed yet. If you've got the document count in the index_stats.json then you could just use that. If that's failing also then obviously it's tied to a bigger problem.  I could get the shards first and just not do the count if there's > 1000 shards now that I know there's a limit.  But that's not all that much better than just going ahead and just writing the error message. It's kind of a convenience call - not sure it would be better to loop through the individual indices getting the count given that 1000 shards would probably indicate a high index count as well.

Open to suggestions here. Just need a bit more info on what else is present and what you're looking for.

**Comment by dakrone** [comment]
> What ES version was the diagnostic run against?

5.0.1

> Whether the /_stats call that produces indices_stats.json ran successfully?

Yes it did, see:

```
  "_all" : {
    "primaries" : {
      "docs" : {
        "count" : 4165029927
```

> Did any of the other REST calls fail?

`/_cat/count` and whatever produces `count.json` (I am assuming a `GET /_search?size=0`) both fail. Other than that it looks like everything works fine.

> Open to suggestions here.

Perhaps generate `count.json` based on the indices stats output rather than a query? (I'm just guessing it's a query). `/_cat/count` is easy to live without.

**Comment by nemonster** [comment]
Apologies here, because this one just slipped completely off my radar. Given that the count is in the indices_stats.json and that the _cat?count isn't that reliable I'm going to just remove it. I don't really parse things out in the diag. I just collect and dump for the most part unless I actually need something in one of the outputs.
