### ISSUE TITLE
Support splitting large diagnostic dumps into smaller files

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-support-diagnostics#160]
It would be cool if the diagnostics tool supported the ability to split the archive it creates into smaller chunks, either when the archive will be over a certain configurable size or into a certain number of chunks.  This would be helpful where transferring the diagnostic is limited by its size for some reason (for example, some website form uploads or email systems).

**Comment by nemonster** [comment]
Can look into that, but what size did you have in mind? Examples? Since I stopped pulling all the logs by default most of these come in < 10mb, which generally isn't an issue. Cluster state is usually the worst offender, but again I'd like to have some specific examples before trying to make any modifications.

**Comment by nemonster** [comment]
Given the recent automation for creating S3 buckets and that I haven't gotten any concrete examples or suggestions on what the proper cutoff size is I'm going to close this one for now.
