### ISSUE TITLE
dmesg with -T option by default

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch-support-diagnostics#161]
I found changing diags.yml for dmesg as below useful as -T option emits readable timestamp.
If -T flag is globally available in various distributions, we might want to make it default.

`  dmesg: "dmesg -T"`

```
[root@haruto support-diagnostics-5.12]# uname -a
Linux haruto 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@haruto support-diagnostics-5.12]# dmesg | head -5
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017
[    0.000000] Command line: BOOT_IMAGE=/vmlinuz-3.10.0-514.16.1.el7.x86_64 root=/dev/mapper/cl-root ro crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet LANG=en_US.UTF-8
[root@haruto support-diagnostics-5.12]# dmesg -T | head -5
[Sat Jul  1 07:33:33 2017] Initializing cgroup subsys cpuset
[Sat Jul  1 07:33:33 2017] Initializing cgroup subsys cpu
[Sat Jul  1 07:33:33 2017] Initializing cgroup subsys cpuacct
[Sat Jul  1 07:33:33 2017] Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017
[Sat Jul  1 07:33:33 2017] Command line: BOOT_IMAGE=/vmlinuz-3.10.0-514.16.1.el7.x86_64 root=/dev/mapper/cl-root ro crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet LANG=en_US.UTF-8
[root@haruto support-diagnostics-5.12]# 
```

**Comment by nemonster** [comment]
A quick Google search doesn't pull up much info on this. If you test it to see if it runs on currently supported ES platforms I might consider changing it, but I'd rather not break what's already there. If you need that information, the diags.yml is easily modified so the first rule here would be "do no harm".

**Comment by jpcarey** [comment]
I would not want this. I'd much rather see seconds from boot, rather than a form of datetime. If you really wanted this, just grab the current OS timestamp (stored in many places in the diagnostic), subtract and format. Ex.
`awk -F'[][]' 'BEGIN {current=systime()} {time=strftime("%a %b %e %H:%M:%S %Z %Y", current-$2,1); $1=$2=""; print time, $0}' dmseg.log`

**Comment by pquentin** [comment]
> I would not want this. I'd much rather see seconds from boot, rather than a form of datetime.

Why is seconds since boot helpful? In my (limited) SDH experience, I would have preferred human readable timestamps because it helps correlating with other symptoms that are also recorded in human readable time, not seconds since boot.

(RHEL 6 *is* an issue, but changing `dmesg` to `dmesg -T || dmesg` should be enough to work around it.)

**Comment by dliappis** [comment]
I second the request for include the `dmesg` output with human timestamps and agree with the argumentation in the comment [above](https://github.com/elastic/support-diagnostics/issues/161#issuecomment-1103775149).

If we absolutely must keep the original `dmesg` output in seconds since boot, I think we can afford including a second variant of the file using `dmesg -T` (or `journalctl -b` in the bundle.

**Comment by inqueue** [comment]
@jpcarey GH access privileges are blocking our ability to reopen this issue. Can you repoen on behalf of the ES perf team in light of https://github.com/elastic/support-diagnostics/issues/161#issuecomment-1103821030 and https://github.com/elastic/support-diagnostics/issues/161#issuecomment-1103775149?

**Comment by PhaedrusTheGreek** [comment]
Grooming Notes
- We should do both because `-T` won't work on all distributions

**Comment by pickypg** [comment]
I just merged a simple change that will go into the next release: it will include a `dmesg_t` file that uses `dmesg -T` as a peer to the `dmesg` file.

This will allow both use cases:

- Ignoring boottime issues
- Figuring out when things actually happened
