### ISSUE TITLE
Store diagnostic execution time with timezone in UTC

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#56]
Storing the timestamp in the directory name is not very persistent/reliable.  Should have a meta file in the directory storing details like host and timestamp.

**Comment by nemonster** [comment]
Are you saying you want it in another place or that you want it removed from the archive filename.  From a diagnostic creation standpoint, including the time stamp in the name removes the need to check for previous runs and then the decision on what to do with that previous run.  I don't have issues with putting adding it to a file but you've already got a number of related and possibly overlapping requests in this general area.

**Comment by nemonster** [comment]
I've already modified the manifest to take out the node related information that used to be in there, leaving only the cluster name, the version of the diagnostic that was run, and a full ISO 8601 date.  Curious on whether the host name really needs to be in there?  Assuming you mean the host it was run on?  Since the various host names are already present elsewhere in the output.

**Comment by robin13** [comment]
Yes - host diagnostics was run on would be great.

**Comment by nemonster** [comment]
host/node diagnostics were run on added as well as run date.
