### ISSUE TITLE
config and logs dir to root

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch-support-diagnostics#81]
The config and logs directory is now in a directory named after the cluster - this makes it more difficult to process automatically... would it be possible to move these back to the root level (like old diagnostics), or is there a good reason I'm missing for having it this way?

**Comment by nemonster** [comment]
If you look carefully you'll see that it's the cluster name plus node name plus "log and config"  That is because if there is more than one node deployed on a given host it will try to collect those logs and configs as well.  There needs to be some way to differentiate.  The cluster name is on there mainly as a convenience because if they let the names get assigned dynamically it can be hard to keep some of them differentiated.  I can't do this request without breaking that functionality.  Your request will only work if there's only going to be one set of logs and configs.

**Comment by robin13** [comment]
As with #82, I would much prefer having each diagnostics related to one node only, but in that be sure: everything in **this** diagnostics **is** to do with the node it was collected on/against.

**Comment by nemonster** [comment]
Deferring any further discussion to when the new unified log format gets solidified.  I'm going to turn this around - I have a really good reason for separating these configurations by node.  I can parse multiple log directories( in the scrubber for instance) with a file mask - I'm having some difficulty understanding why this is a showstopper in this code.
