### ISSUE TITLE
Report whether Compressed OOPs are in use

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch-support-diagnostics#85]
> jinfo -flag UseCompressedOops $(jps|grep Elasticsearch| awk '{ print $1 }')

**Comment by nemonster** [comment]
I don't have any particular concern about adding another system call.  However, I would have a couple of questions/concerns with regards to just adding this particular one.

* Does it need to be run as sudo or the same account running the Elasticsearch node?  If so, that's another additional run requirement, at least if you want output.
* What happens if there's more than one node running on that host?  I haven't tried that, but given that all that's specified here is a snippet I'd like to think that any side effects would be considered.
* Just Linux?  Windows?  I ran it on my Mac just now and it didn't work.  Although I have multiple instances running...

It's only an issue when there's no Xmx or Xmx is > 32G.  The command only runs on the host the diagnostic is being run on.  So there's a certain degree of chance involved if not all nodes are configured consistently for heap.  Like any of the system calls we make, the degree of utility it provides can vary depending on the consistency of the configurations from a host or node perspective.

My other question would be that given that it can be kind of a corner case, you would probably have a pretty good indication of whether or not this would be an issue?  So if you have the actual argument/parameter list for the process, as well as the heap size for the node the script was run on and all the others, is this really necessary?  Are the absence of Xmx or a heap > 32G not reliable enough indicators?

**Comment by GlenRSmith** [comment]
@nemonster Very good points. As much as anything, I wanted to have the conversation, and capture the darn call in an easy place to find for ad hoc purposes.

> It's only an issue when there's no Xmx or Xmx is > 32G

Not so. There's a great deal of variability OS to OS and runtime to runtime as to where compressed OOPS get disabled. Hence the "conventional wisdom" of 30.5G, because it's thought to be a safe setting for all platforms. Sufficient, but not necessary. I just thought it would be rather nice to just - ask the JVM if they are in use. 

Now I remember what I was doing when my internet went out  a while ago: I was adding the comment that, from 2.2 forward, this will actually be in the nodes info API's "jvm" object:

`"using_compressed_ordinary_object_pointers" : "true"`

which is nice. :-)
