### ISSUE TITLE
Add kernel log to support diagnostics

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch-support-diagnostics#96]
Make an attempt to grab the kernel log and/or `dmesg` output when support diagnostics is not executed remotely. Support diagnostic requirements:

* must be executed as root or with `sudo`
* must be executed on a node that is under duress

This would hopefully help diagnose network related or IO issues that are preventing Elastic software from performing adequately. See this [support ticket](https://elasticsearch.zendesk.com/agent/tickets/21538) for an example where this would have been really helpful.

It could potentially be problematic to execute REST API requests on such a node. Maybe instead the diagnostics instead needs a local option or set of options that requires root or sudo which collects possible variations of:

* dmesg
* kernel log
* jstack
* heap dump (optional)
* jstat
* ES logs
* netstat or ss
* iostat
* vmstat
* other local items already included
* anything else I'm not thinking of

**Comment by nemonster** [comment]
I'm not exactly sure what you're looking for here?  Something to run a number of system commands, aggregate and archive the results *is* possible.  But for instance, you don't necessarily know where the logs are.  The diagnostic knows because it's run the _nodes REST call which tells it the exact location from parsing out the returned JSON.  

And it's getting ss *and* netstat currently for Linux systems.  So I'm also not sure why those current implementations don't work for you?  That does bring up the issue that some of these such as iostat have a number of options IIRC, some of which are kind of mutually exclusive.  So exactly what flavor of these are we talking here?

Again, I don't have any philosophical issue with adding that kind of functionality.  But short term, this seems to reflect corner cases.  And you still have to run it on every node you're interested in.  Keep in mind that in the current utility you can add as many extra calls as you want.  All that's required is to add an entry for each to the diagnostics.yml.  So short term, if you wanted additional calls all you'd have to do is attach an updated version and tell the customer to drop that in before running.  Now currently, that would still get the REST statistics but I can always add an option to execute only the command line pieces as mentioned before.

In addition, if they are running this and these commands need to be sudo, I have to admit I haven't figured out how to determine from the running Java process yet whether it's running at a sufficient level other than just try and fail.  Which brings up the issue of how I'll figure that out during runtime and report it as such.  Keep in mind I just had a number of issues, such as some of the log requests and the one to bypass SSL hostname verification are concerned with making it easier to run this thing without knowing what you're doing.  And this is appears to head in the opposite direction since they at least need to be aware of how sudo works so I'd rather this one be fairly detailed and well scoped before I dive to far in.

**Comment by inqueue** [comment]
I think there are just too many unknowns to do this in the existing support diagnostics. We'll just have to manually request the info needed to troubleshoot a system outside of the Elasticsearch process as the list of bullet points above are intended to gather information when the service isn't necessarily stable.
